---
title: "FYP_project_4_sketching"
author: "Nicolaj Valsted"
date: "23/4/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 2 sketching

```{r}
library("ggplot2")
theme_set(theme_bw())
library("sf")
library("ggspatial")
library("UsingR")
library("rmarkdown")
library("grid")
```

```{r}
map_landsdele <- read_sf("E:/pile_of_data/FYP4/DAGI/dagi_10m_nohist_l1.landsdel/landsdel.shp")

map_landsdele$area <- as.numeric(st_area(map_landsdele))

```

```{r}
map_landsdele
```


```{r}
ggplot() +
  geom_sf(data = map_landsdele, size = 0.5) +
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
  ggtitle("Bornholm") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        plot.title  = element_text(size = 8)) +
  coord_sf(xlim = c(855000, 900000), ylim = c(6105000, 6150000), expand=FALSE)
```

```{r}
main_plot <- ggplot() +
  geom_sf(data = map_landsdele, size = 0.5, aes(fill = area)) +
  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
  annotation_scale(location = "bl", width_hint = 0.4) +
  xlab("Longitude") + ylab("Latitude") +
  ggtitle("Denmark",subtitle = "landsdele") +
  coord_sf(xlim = c(420000, 750000), ylim = c(6030000, 6420000), expand=FALSE)

#bornholm_plot <- ggplot() +
#  geom_sf(data = map_landsdele, size = 0.5) +
#  scale_fill_viridis_c(trans = "sqrt", alpha = .4) +
#  ggtitle("Bornholm") +
#  theme(axis.text.x = element_blank(),
#        axis.text.y = element_blank(),
#        plot.title  = element_text(size = 8)) +
#  coord_sf(xlim = c(855000, 900000), ylim = c(6105000, 6150000), expand=FALSE)

vp <- viewport(width = 0.2, height = 0.2, x = 0.725, y = 0.8)

pdf("Map_draft.pdf")

print(main_plot)
print(bornholm_plot, vp=vp)

#dev.off()
```

